import 'dart:convert';

import 'package:coffee_shop_app/component/coffee_title.dart';
import 'package:coffee_shop_app/models/coffee.dart';
import 'package:coffee_shop_app/models/coffee_shop.dart';
import 'package:coffee_shop_app/models/json_model.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:http/http.dart' as http;

class CartPage extends StatefulWidget {
  const CartPage({super.key});

  @override
  State<CartPage> createState() => _CartPageState();
}

class _CartPageState extends State<CartPage> {
  // this is because i don't have the array name
  List<Autogenerated> postList = [];
  getApiCall() async {
    final response =
        await http.get(Uri.parse("https://jsonplaceholder.typicode.com/users"));

    var data = jsonDecode(response.body.toString());
    // if response statusCode hit the 200 this mean api successfully hit
    if (response.statusCode == 200) {
      for (var i in data) {
        postList.add(Autogenerated.fromJson(i));
      }
      return postList;
    }
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: getApiCall(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Text("data");
          } else {
            return ListView.builder(
              itemCount: postList.length,
              itemBuilder: (context, index) {
                return Column(
                  children: [
                    Text(postList[index].name.toString()),
                    Text(postList[index].id.toString()),
                    Text(postList[index].username.toString()),
                    Text(postList[index].address.toString()),
                    const Text("this is data"),
                    Text(postList[index].address!.city.toString()),
                    Text(postList[index].company.toString()),
                    Text(postList[index].website.toString()),
                    Text(postList[index].phone.toString()),
                    Text(postList[index].email.toString()),
                  ],
                );
              },
            );
          }
        });
  }
}
